# Generated by Django 4.2.5 on 2023-09-17 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(default='student_login', max_length=100)),
                ('course_enrolled', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('preferred_name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(default='teacher_login', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('morning_break_status', models.CharField(max_length=20)),
                ('morning_break_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('lunch_break_status', models.CharField(max_length=20)),
                ('lunch_break_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tea_break_status', models.CharField(max_length=20)),
                ('tea_break_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('final_session_status', models.CharField(max_length=20)),
                ('final_session_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('total_class_hours', models.DecimalField(decimal_places=2, max_digits=4)),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.teacher')),
            ],
            options={
                'unique_together': {('student', 'class_info', 'trainer')},
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('module', models.CharField(max_length=100)),
                ('class_total', models.PositiveIntegerField()),
                ('class_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.class')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.teacher')),
            ],
            options={
                'unique_together': {('class_info', 'trainer')},
            },
        ),
    ]
